# Generated by Django 4.2.7 on 2023-11-01 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('qoshilgan_sana', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Suhbat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=50)),
                ('fayl', models.FileField(upload_to='')),
                ('davomiylik', models.CharField(blank=True, max_length=50, null=True)),
                ('hajm', models.CharField(blank=True, max_length=50, null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiyApp.topic')),
            ],
        ),
    ]
